services:
 minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: quickdrive
      MINIO_ROOT_PASSWORD: quick123123
    volumes:
      - minio_data:/data
    deploy:
      restart_policy:
        condition: any

volumes:
  minio_data: